#ifndef STORAGEMANAGERCOMMON
#define STORAGEMANAGERCOMMON

#define DISKMANAGER_HEADERSIZE 16
#define DISKMANAGER_PAGESIZE 255
#define DISK_NULL 0
#define PAGE_FILL '0'
#define FREE_PAGE_HEADER_SIZE 2
#endif