#ifndef STORAGEMANAGERCOMMON
#define STORAGEMANAGERCOMMON

#define DISKMANAGER_HEADERSIZE 8
#define DISKMANAGER_POINTERSIZE 4
#define DISKMANAGER_PAGESIZE 256
#define DISK_NULL 0
#define PAGE_FILL 'A'
#endif